"""reservas de estoque

Revision ID: 0212672551d6
Revises: 47808396340e
Create Date: 2026-09-23 09:58:44.514837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0212672551d6'
down_revision: Union[str, Sequence[str], None] = '47808396340e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estoque_reservas',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('saldo_id', sa.String(length=100), nullable=False),
    sa.Column('produto_id', sa.String(length=100), nullable=False),
    sa.Column('deposito_id', sa.String(length=100), nullable=False),
    sa.Column('gaveta_id', sa.String(length=100), nullable=False),
    sa.Column('lote_id', sa.String(length=100), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('origem_modulo', sa.String(length=50), nullable=False),
    sa.Column('documento_origem_id', sa.String(length=100), nullable=False),
    sa.Column('referencia', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.String(length=100), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('consumida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelada_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estoque_reservas_deposito_id'), 'estoque_reservas', ['deposito_id'], unique=False)
    op.create_index(op.f('ix_estoque_reservas_documento_origem_id'), 'estoque_reservas', ['documento_origem_id'], unique=False)
    op.create_index(op.f('ix_estoque_reservas_gaveta_id'), 'estoque_reservas', ['gaveta_id'], unique=False)
    op.create_index(op.f('ix_estoque_reservas_lote_id'), 'estoque_reservas', ['lote_id'], unique=False)
    op.create_index(op.f('ix_estoque_reservas_origem_modulo'), 'estoque_reservas', ['origem_modulo'], unique=False)
    op.create_index(op.f('ix_estoque_reservas_produto_id'), 'estoque_reservas', ['produto_id'], unique=False)
    op.create_index(op.f('ix_estoque_reservas_saldo_id'), 'estoque_reservas', ['saldo_id'], unique=False)
    op.create_index(op.f('ix_estoque_reservas_status'), 'estoque_reservas', ['status'], unique=False)
    op.create_index(op.f('ix_estoque_reservas_usuario_id'), 'estoque_reservas', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estoque_reservas_usuario_id'), table_name='estoque_reservas')
    op.drop_index(op.f('ix_estoque_reservas_status'), table_name='estoque_reservas')
    op.drop_index(op.f('ix_estoque_reservas_saldo_id'), table_name='estoque_reservas')
    op.drop_index(op.f('ix_estoque_reservas_produto_id'), table_name='estoque_reservas')
    op.drop_index(op.f('ix_estoque_reservas_origem_modulo'), table_name='estoque_reservas')
    op.drop_index(op.f('ix_estoque_reservas_lote_id'), table_name='estoque_reservas')
    op.drop_index(op.f('ix_estoque_reservas_gaveta_id'), table_name='estoque_reservas')
    op.drop_index(op.f('ix_estoque_reservas_documento_origem_id'), table_name='estoque_reservas')
    op.drop_index(op.f('ix_estoque_reservas_deposito_id'), table_name='estoque_reservas')
    op.drop_table('estoque_reservas')
    # ### end Alembic commands ###
