"""auditoria das reservas

Revision ID: 2545e315dc66
Revises: b21fc76b6fed
Create Date: 2026-09-23 10:02:03.267562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2545e315dc66'
down_revision: Union[str, Sequence[str], None] = 'b21fc76b6fed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estoque_reserva_eventos',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('reserva_id', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('usuario_id', sa.String(length=100), nullable=False),
    sa.Column('documento_estoque_id', sa.String(length=100), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estoque_reserva_eventos_created_at'), 'estoque_reserva_eventos', ['created_at'], unique=False)
    op.create_index(op.f('ix_estoque_reserva_eventos_documento_estoque_id'), 'estoque_reserva_eventos', ['documento_estoque_id'], unique=False)
    op.create_index(op.f('ix_estoque_reserva_eventos_reserva_id'), 'estoque_reserva_eventos', ['reserva_id'], unique=False)
    op.create_index(op.f('ix_estoque_reserva_eventos_tipo'), 'estoque_reserva_eventos', ['tipo'], unique=False)
    op.create_index(op.f('ix_estoque_reserva_eventos_usuario_id'), 'estoque_reserva_eventos', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estoque_reserva_eventos_usuario_id'), table_name='estoque_reserva_eventos')
    op.drop_index(op.f('ix_estoque_reserva_eventos_tipo'), table_name='estoque_reserva_eventos')
    op.drop_index(op.f('ix_estoque_reserva_eventos_reserva_id'), table_name='estoque_reserva_eventos')
    op.drop_index(op.f('ix_estoque_reserva_eventos_documento_estoque_id'), table_name='estoque_reserva_eventos')
    op.drop_index(op.f('ix_estoque_reserva_eventos_created_at'), table_name='estoque_reserva_eventos')
    op.drop_table('estoque_reserva_eventos')
    # ### end Alembic commands ###
