"""unidades profissionais estoque

Revision ID: 47808396340e
Revises: a518c4f5ea0b
Create Date: 2026-09-23 09:54:07.113276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47808396340e'
down_revision: Union[str, Sequence[str], None] = 'a518c4f5ea0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estoque_documento_itens', sa.Column('quantidade_informada', sa.Numeric(precision=18, scale=3), nullable=True))
    op.add_column('estoque_documento_itens', sa.Column('unidade_informada', sa.String(length=30), nullable=True))
    op.add_column('estoque_documento_itens', sa.Column('fator_conversao', sa.Numeric(precision=18, scale=6), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estoque_documento_itens', 'fator_conversao')
    op.drop_column('estoque_documento_itens', 'unidade_informada')
    op.drop_column('estoque_documento_itens', 'quantidade_informada')
    # ### end Alembic commands ###
