"""ie no cadastro de pessoas

Revision ID: 81ef759bea80
Revises: 0e99f605099a
Create Date: 2026-09-23 10:33:56.333751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ef759bea80'
down_revision: Union[str, Sequence[str], None] = '0e99f605099a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoas', sa.Column('ie', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_pessoas_ie'), 'pessoas', ['ie'], unique=False)
    op.create_index(op.f('ix_pessoas_is_transportadora'), 'pessoas', ['is_transportadora'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pessoas_is_transportadora'), table_name='pessoas')
    op.drop_index(op.f('ix_pessoas_ie'), table_name='pessoas')
    op.drop_column('pessoas', 'ie')
    # ### end Alembic commands ###
