"""estrutura inicial

Revision ID: 915e8b022744
Revises:
Create Date: 2026-09-23 08:27:19.020363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '915e8b022744'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abastecimentos',
    sa.Column('data', sa.DateTime(timezone=True), nullable=False),
    sa.Column('maquina_id', sa.String(length=100), nullable=False),
    sa.Column('produto_id', sa.String(length=100), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('unidade', sa.String(length=30), nullable=True),
    sa.Column('operador', sa.String(length=255), nullable=True),
    sa.Column('numero_mov', sa.String(length=100), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('foto_url', sa.Text(), nullable=True),
    sa.Column('confirmado_por', sa.String(length=255), nullable=True),
    sa.Column('data_confirmacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abastecimentos_created_by_id'), 'abastecimentos', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_abastecimentos_maquina_id'), 'abastecimentos', ['maquina_id'], unique=False)
    op.create_index(op.f('ix_abastecimentos_produto_id'), 'abastecimentos', ['produto_id'], unique=False)
    op.create_index(op.f('ix_abastecimentos_status'), 'abastecimentos', ['status'], unique=False)
    op.create_table('anos_safra',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anos_safra_created_by_id'), 'anos_safra', ['created_by_id'], unique=False)
    op.create_table('culturas',
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_culturas_created_by_id'), 'culturas', ['created_by_id'], unique=False)
    op.create_table('depositos',
    sa.Column('numero', sa.String(length=100), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('setor_id', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_depositos_created_by_id'), 'depositos', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_depositos_numero'), 'depositos', ['numero'], unique=False)
    op.create_index(op.f('ix_depositos_setor_id'), 'depositos', ['setor_id'], unique=False)
    op.create_table('gavetas',
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('deposito_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gavetas_codigo'), 'gavetas', ['codigo'], unique=False)
    op.create_index(op.f('ix_gavetas_created_by_id'), 'gavetas', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_gavetas_deposito_id'), 'gavetas', ['deposito_id'], unique=False)
    op.create_table('inventario_itens',
    sa.Column('inventario_id', sa.String(length=100), nullable=False),
    sa.Column('produto_id', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('unidade', sa.String(length=30), nullable=True),
    sa.Column('qtd_sistema', sa.Float(), nullable=True),
    sa.Column('qtd_contada', sa.Float(), nullable=False),
    sa.Column('responsavel', sa.String(length=255), nullable=True),
    sa.Column('data', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventario_itens_created_by_id'), 'inventario_itens', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_inventario_itens_inventario_id'), 'inventario_itens', ['inventario_id'], unique=False)
    op.create_index(op.f('ix_inventario_itens_produto_id'), 'inventario_itens', ['produto_id'], unique=False)
    op.create_table('inventarios',
    sa.Column('numero', sa.String(length=100), nullable=True),
    sa.Column('data', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_fechamento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('setor_id', sa.String(length=100), nullable=False),
    sa.Column('setor_nome', sa.String(length=255), nullable=True),
    sa.Column('criterios', sa.Text(), nullable=True),
    sa.Column('criterios_descricao', sa.Text(), nullable=True),
    sa.Column('itens', sa.Text(), nullable=True),
    sa.Column('total_itens', sa.Float(), nullable=True),
    sa.Column('total_acertos', sa.Float(), nullable=True),
    sa.Column('total_divergencias', sa.Float(), nullable=True),
    sa.Column('resultado', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('responsavel', sa.String(length=255), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventarios_created_by_id'), 'inventarios', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_inventarios_numero'), 'inventarios', ['numero'], unique=False)
    op.create_index(op.f('ix_inventarios_setor_id'), 'inventarios', ['setor_id'], unique=False)
    op.create_index(op.f('ix_inventarios_status'), 'inventarios', ['status'], unique=False)
    op.create_table('lavouras',
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=100), nullable=True),
    sa.Column('hectares', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lavouras_created_by_id'), 'lavouras', ['created_by_id'], unique=False)
    op.create_table('lotes',
    sa.Column('produto_id', sa.String(length=100), nullable=False),
    sa.Column('codigo_referencia', sa.String(length=255), nullable=True),
    sa.Column('setor_id', sa.String(length=100), nullable=True),
    sa.Column('deposito_id', sa.String(length=100), nullable=True),
    sa.Column('maquina_id', sa.String(length=100), nullable=True),
    sa.Column('gaveta_id', sa.String(length=100), nullable=True),
    sa.Column('codigo_lote', sa.String(length=150), nullable=False),
    sa.Column('data_validade', sa.Date(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('unidade', sa.String(length=30), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lotes_codigo_lote'), 'lotes', ['codigo_lote'], unique=False)
    op.create_index(op.f('ix_lotes_created_by_id'), 'lotes', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_lotes_deposito_id'), 'lotes', ['deposito_id'], unique=False)
    op.create_index(op.f('ix_lotes_gaveta_id'), 'lotes', ['gaveta_id'], unique=False)
    op.create_index(op.f('ix_lotes_maquina_id'), 'lotes', ['maquina_id'], unique=False)
    op.create_index(op.f('ix_lotes_produto_id'), 'lotes', ['produto_id'], unique=False)
    op.create_index(op.f('ix_lotes_setor_id'), 'lotes', ['setor_id'], unique=False)
    op.create_table('maquinas',
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('deposito_id', sa.String(length=100), nullable=True),
    sa.Column('permite_abastecimento', sa.Boolean(), nullable=True),
    sa.Column('combustivel_id', sa.String(length=100), nullable=True),
    sa.Column('combustivel_nome', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maquinas_codigo'), 'maquinas', ['codigo'], unique=False)
    op.create_index(op.f('ix_maquinas_combustivel_id'), 'maquinas', ['combustivel_id'], unique=False)
    op.create_index(op.f('ix_maquinas_created_by_id'), 'maquinas', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_maquinas_deposito_id'), 'maquinas', ['deposito_id'], unique=False)
    op.create_table('movimentacoes',
    sa.Column('numero', sa.String(length=100), nullable=True),
    sa.Column('data', sa.DateTime(timezone=True), nullable=False),
    sa.Column('produto_id', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=True),
    sa.Column('nome_produto', sa.String(length=255), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('custo_unitario', sa.Float(), nullable=True),
    sa.Column('valor_movimentado', sa.Float(), nullable=True),
    sa.Column('setor_id', sa.String(length=100), nullable=True),
    sa.Column('deposito_id', sa.String(length=100), nullable=True),
    sa.Column('maquina_id', sa.String(length=100), nullable=True),
    sa.Column('gaveta_id', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('modulo', sa.String(length=100), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('numero_nf', sa.String(length=100), nullable=True),
    sa.Column('fornecedor', sa.String(length=255), nullable=True),
    sa.Column('chave_acesso', sa.String(length=100), nullable=True),
    sa.Column('lote_id', sa.String(length=100), nullable=True),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('lotes_consumidos', sa.Text(), nullable=True),
    sa.Column('estornada', sa.Boolean(), nullable=True),
    sa.Column('estorno_de', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentacoes_chave_acesso'), 'movimentacoes', ['chave_acesso'], unique=False)
    op.create_index(op.f('ix_movimentacoes_created_by_id'), 'movimentacoes', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_data'), 'movimentacoes', ['data'], unique=False)
    op.create_index(op.f('ix_movimentacoes_deposito_id'), 'movimentacoes', ['deposito_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_estornada'), 'movimentacoes', ['estornada'], unique=False)
    op.create_index(op.f('ix_movimentacoes_estorno_de'), 'movimentacoes', ['estorno_de'], unique=False)
    op.create_index(op.f('ix_movimentacoes_gaveta_id'), 'movimentacoes', ['gaveta_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_lote_id'), 'movimentacoes', ['lote_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_maquina_id'), 'movimentacoes', ['maquina_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_modulo'), 'movimentacoes', ['modulo'], unique=False)
    op.create_index(op.f('ix_movimentacoes_numero'), 'movimentacoes', ['numero'], unique=False)
    op.create_index(op.f('ix_movimentacoes_produto_id'), 'movimentacoes', ['produto_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_setor_id'), 'movimentacoes', ['setor_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_tipo'), 'movimentacoes', ['tipo'], unique=False)
    op.create_table('ordens_servico_aplicacao',
    sa.Column('numero', sa.String(length=100), nullable=False),
    sa.Column('cultura_id', sa.String(length=100), nullable=True),
    sa.Column('cultura_nome', sa.String(length=255), nullable=True),
    sa.Column('ano_safra', sa.String(length=100), nullable=True),
    sa.Column('lavoura_id', sa.String(length=100), nullable=False),
    sa.Column('lavoura_nome', sa.String(length=255), nullable=True),
    sa.Column('hectares', sa.Float(), nullable=False),
    sa.Column('itens', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('data', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_execucao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responsavel', sa.String(length=255), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('custo_total', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordens_servico_aplicacao_ano_safra'), 'ordens_servico_aplicacao', ['ano_safra'], unique=False)
    op.create_index(op.f('ix_ordens_servico_aplicacao_created_by_id'), 'ordens_servico_aplicacao', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_ordens_servico_aplicacao_cultura_id'), 'ordens_servico_aplicacao', ['cultura_id'], unique=False)
    op.create_index(op.f('ix_ordens_servico_aplicacao_lavoura_id'), 'ordens_servico_aplicacao', ['lavoura_id'], unique=False)
    op.create_index(op.f('ix_ordens_servico_aplicacao_numero'), 'ordens_servico_aplicacao', ['numero'], unique=False)
    op.create_index(op.f('ix_ordens_servico_aplicacao_status'), 'ordens_servico_aplicacao', ['status'], unique=False)
    op.create_table('pagamentos',
    sa.Column('numero', sa.String(length=100), nullable=True),
    sa.Column('pedido_id', sa.String(length=100), nullable=False),
    sa.Column('cliente_id', sa.String(length=100), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=30), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagamentos_cliente_id'), 'pagamentos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_pagamentos_created_by_id'), 'pagamentos', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_pagamentos_numero'), 'pagamentos', ['numero'], unique=False)
    op.create_index(op.f('ix_pagamentos_pedido_id'), 'pagamentos', ['pedido_id'], unique=False)
    op.create_table('pedidos_pesagem',
    sa.Column('numero', sa.String(length=100), nullable=True),
    sa.Column('cliente_id', sa.String(length=100), nullable=False),
    sa.Column('produto_id', sa.String(length=100), nullable=False),
    sa.Column('transportadora_ids', sa.Text(), nullable=True),
    sa.Column('transportadora_nomes', sa.Text(), nullable=True),
    sa.Column('sem_limite', sa.Boolean(), nullable=True),
    sa.Column('peso_saca_kg', sa.Float(), nullable=True),
    sa.Column('valor_saca', sa.Float(), nullable=True),
    sa.Column('qtd_sacas', sa.Float(), nullable=True),
    sa.Column('total_kg', sa.Float(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('saldo_kg', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_pesagem_cliente_id'), 'pedidos_pesagem', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_pedidos_pesagem_created_by_id'), 'pedidos_pesagem', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_pedidos_pesagem_numero'), 'pedidos_pesagem', ['numero'], unique=False)
    op.create_index(op.f('ix_pedidos_pesagem_produto_id'), 'pedidos_pesagem', ['produto_id'], unique=False)
    op.create_index(op.f('ix_pedidos_pesagem_status'), 'pedidos_pesagem', ['status'], unique=False)
    op.create_table('pessoas',
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('documento', sa.String(length=50), nullable=True),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.Column('cidade', sa.String(length=150), nullable=True),
    sa.Column('uf', sa.String(length=10), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('cnh', sa.String(length=100), nullable=True),
    sa.Column('cnh_validade', sa.Date(), nullable=True),
    sa.Column('is_cliente', sa.Boolean(), nullable=True),
    sa.Column('is_fornecedor', sa.Boolean(), nullable=True),
    sa.Column('is_transportadora', sa.Boolean(), nullable=True),
    sa.Column('is_motorista', sa.Boolean(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pessoas_created_by_id'), 'pessoas', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_pessoas_documento'), 'pessoas', ['documento'], unique=False)
    op.create_index(op.f('ix_pessoas_is_cliente'), 'pessoas', ['is_cliente'], unique=False)
    op.create_index(op.f('ix_pessoas_is_fornecedor'), 'pessoas', ['is_fornecedor'], unique=False)
    op.create_index(op.f('ix_pessoas_is_motorista'), 'pessoas', ['is_motorista'], unique=False)
    op.create_index(op.f('ix_pessoas_nome'), 'pessoas', ['nome'], unique=False)
    op.create_table('produtos',
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('codigo_referencia', sa.String(length=255), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('setor_id', sa.String(length=100), nullable=False),
    sa.Column('deposito_id', sa.String(length=100), nullable=True),
    sa.Column('maquina_id', sa.String(length=100), nullable=True),
    sa.Column('gaveta_id', sa.String(length=100), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('unidade', sa.String(length=30), nullable=True),
    sa.Column('unidade_alt', sa.String(length=30), nullable=True),
    sa.Column('fator_conversao', sa.Float(), nullable=True),
    sa.Column('estoque_minimo', sa.Float(), nullable=True),
    sa.Column('custo_unitario', sa.Float(), nullable=True),
    sa.Column('venda', sa.Boolean(), nullable=True),
    sa.Column('foto_url', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_codigo'), 'produtos', ['codigo'], unique=False)
    op.create_index(op.f('ix_produtos_codigo_referencia'), 'produtos', ['codigo_referencia'], unique=False)
    op.create_index(op.f('ix_produtos_created_by_id'), 'produtos', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_produtos_deposito_id'), 'produtos', ['deposito_id'], unique=False)
    op.create_index(op.f('ix_produtos_gaveta_id'), 'produtos', ['gaveta_id'], unique=False)
    op.create_index(op.f('ix_produtos_maquina_id'), 'produtos', ['maquina_id'], unique=False)
    op.create_index(op.f('ix_produtos_nome'), 'produtos', ['nome'], unique=False)
    op.create_index(op.f('ix_produtos_setor_id'), 'produtos', ['setor_id'], unique=False)
    op.create_index(op.f('ix_produtos_venda'), 'produtos', ['venda'], unique=False)
    op.create_table('saldos_estoque',
    sa.Column('produto_id', sa.String(length=100), nullable=False),
    sa.Column('deposito_id', sa.String(length=100), nullable=False),
    sa.Column('gaveta_id', sa.String(length=100), nullable=True),
    sa.Column('lote_id', sa.String(length=100), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('custo_unitario', sa.Float(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('unidade', sa.String(length=30), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saldos_estoque_created_by_id'), 'saldos_estoque', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_saldos_estoque_deposito_id'), 'saldos_estoque', ['deposito_id'], unique=False)
    op.create_index(op.f('ix_saldos_estoque_gaveta_id'), 'saldos_estoque', ['gaveta_id'], unique=False)
    op.create_index(op.f('ix_saldos_estoque_lote_id'), 'saldos_estoque', ['lote_id'], unique=False)
    op.create_index(op.f('ix_saldos_estoque_produto_id'), 'saldos_estoque', ['produto_id'], unique=False)
    op.create_table('setores',
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('cor', sa.String(length=30), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('controla_validade', sa.Boolean(), nullable=True),
    sa.Column('tem_aba_mobile', sa.Boolean(), nullable=True),
    sa.Column('permite_inventario', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setores_created_by_id'), 'setores', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_setores_nome'), 'setores', ['nome'], unique=False)
    op.create_table('tickets_pesagem',
    sa.Column('numero', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('produto_id', sa.String(length=100), nullable=True),
    sa.Column('cliente_id', sa.String(length=100), nullable=True),
    sa.Column('cliente_nome', sa.String(length=255), nullable=True),
    sa.Column('transportadora_id', sa.String(length=100), nullable=True),
    sa.Column('transportadora_nome', sa.String(length=255), nullable=True),
    sa.Column('origem', sa.String(length=255), nullable=True),
    sa.Column('destino', sa.String(length=255), nullable=True),
    sa.Column('data_abertura', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_fechamento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motorista', sa.String(length=255), nullable=False),
    sa.Column('placa', sa.String(length=30), nullable=False),
    sa.Column('peso_tara', sa.Float(), nullable=False),
    sa.Column('peso_bruto', sa.Float(), nullable=True),
    sa.Column('peso_liquido', sa.Float(), nullable=True),
    sa.Column('pedido_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('nfe_importada', sa.Boolean(), nullable=True),
    sa.Column('nfe_numero', sa.String(length=100), nullable=True),
    sa.Column('nfe_produto', sa.String(length=255), nullable=True),
    sa.Column('nfe_motorista', sa.String(length=255), nullable=True),
    sa.Column('nfe_chave', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_pesagem_cliente_id'), 'tickets_pesagem', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_tickets_pesagem_created_by_id'), 'tickets_pesagem', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_tickets_pesagem_data_abertura'), 'tickets_pesagem', ['data_abertura'], unique=False)
    op.create_index(op.f('ix_tickets_pesagem_nfe_chave'), 'tickets_pesagem', ['nfe_chave'], unique=False)
    op.create_index(op.f('ix_tickets_pesagem_numero'), 'tickets_pesagem', ['numero'], unique=False)
    op.create_index(op.f('ix_tickets_pesagem_pedido_id'), 'tickets_pesagem', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_tickets_pesagem_placa'), 'tickets_pesagem', ['placa'], unique=False)
    op.create_index(op.f('ix_tickets_pesagem_produto_id'), 'tickets_pesagem', ['produto_id'], unique=False)
    op.create_index(op.f('ix_tickets_pesagem_status'), 'tickets_pesagem', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_pesagem_tipo'), 'tickets_pesagem', ['tipo'], unique=False)
    op.create_index(op.f('ix_tickets_pesagem_transportadora_id'), 'tickets_pesagem', ['transportadora_id'], unique=False)
    op.create_table('transportadoras',
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('documento', sa.String(length=50), nullable=True),
    sa.Column('ie', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.Column('cidade', sa.String(length=150), nullable=True),
    sa.Column('uf', sa.String(length=10), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transportadoras_created_by_id'), 'transportadoras', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_transportadoras_documento'), 'transportadoras', ['documento'], unique=False)
    op.create_index(op.f('ix_transportadoras_nome'), 'transportadoras', ['nome'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('pode_confirmar_abastecimento', sa.Boolean(), nullable=True),
    sa.Column('pode_digitar_peso', sa.Boolean(), nullable=True),
    sa.Column('paginas_permitidas', sa.Text(), nullable=True),
    sa.Column('setores_permitidos', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_by_id'), 'users', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('veiculos',
    sa.Column('placa', sa.String(length=30), nullable=False),
    sa.Column('modelo', sa.String(length=255), nullable=True),
    sa.Column('cor', sa.String(length=100), nullable=True),
    sa.Column('ano', sa.String(length=20), nullable=True),
    sa.Column('tara', sa.Float(), nullable=True),
    sa.Column('capacidade_kg', sa.Float(), nullable=True),
    sa.Column('transportadora_id', sa.String(length=100), nullable=True),
    sa.Column('motorista_id', sa.String(length=100), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veiculos_created_by_id'), 'veiculos', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_veiculos_motorista_id'), 'veiculos', ['motorista_id'], unique=False)
    op.create_index(op.f('ix_veiculos_placa'), 'veiculos', ['placa'], unique=False)
    op.create_index(op.f('ix_veiculos_transportadora_id'), 'veiculos', ['transportadora_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_veiculos_transportadora_id'), table_name='veiculos')
    op.drop_index(op.f('ix_veiculos_placa'), table_name='veiculos')
    op.drop_index(op.f('ix_veiculos_motorista_id'), table_name='veiculos')
    op.drop_index(op.f('ix_veiculos_created_by_id'), table_name='veiculos')
    op.drop_table('veiculos')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_by_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transportadoras_nome'), table_name='transportadoras')
    op.drop_index(op.f('ix_transportadoras_documento'), table_name='transportadoras')
    op.drop_index(op.f('ix_transportadoras_created_by_id'), table_name='transportadoras')
    op.drop_table('transportadoras')
    op.drop_index(op.f('ix_tickets_pesagem_transportadora_id'), table_name='tickets_pesagem')
    op.drop_index(op.f('ix_tickets_pesagem_tipo'), table_name='tickets_pesagem')
    op.drop_index(op.f('ix_tickets_pesagem_status'), table_name='tickets_pesagem')
    op.drop_index(op.f('ix_tickets_pesagem_produto_id'), table_name='tickets_pesagem')
    op.drop_index(op.f('ix_tickets_pesagem_placa'), table_name='tickets_pesagem')
    op.drop_index(op.f('ix_tickets_pesagem_pedido_id'), table_name='tickets_pesagem')
    op.drop_index(op.f('ix_tickets_pesagem_numero'), table_name='tickets_pesagem')
    op.drop_index(op.f('ix_tickets_pesagem_nfe_chave'), table_name='tickets_pesagem')
    op.drop_index(op.f('ix_tickets_pesagem_data_abertura'), table_name='tickets_pesagem')
    op.drop_index(op.f('ix_tickets_pesagem_created_by_id'), table_name='tickets_pesagem')
    op.drop_index(op.f('ix_tickets_pesagem_cliente_id'), table_name='tickets_pesagem')
    op.drop_table('tickets_pesagem')
    op.drop_index(op.f('ix_setores_nome'), table_name='setores')
    op.drop_index(op.f('ix_setores_created_by_id'), table_name='setores')
    op.drop_table('setores')
    op.drop_index(op.f('ix_saldos_estoque_produto_id'), table_name='saldos_estoque')
    op.drop_index(op.f('ix_saldos_estoque_lote_id'), table_name='saldos_estoque')
    op.drop_index(op.f('ix_saldos_estoque_gaveta_id'), table_name='saldos_estoque')
    op.drop_index(op.f('ix_saldos_estoque_deposito_id'), table_name='saldos_estoque')
    op.drop_index(op.f('ix_saldos_estoque_created_by_id'), table_name='saldos_estoque')
    op.drop_table('saldos_estoque')
    op.drop_index(op.f('ix_produtos_venda'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_setor_id'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_nome'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_maquina_id'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_gaveta_id'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_deposito_id'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_created_by_id'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_codigo_referencia'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_codigo'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_pessoas_nome'), table_name='pessoas')
    op.drop_index(op.f('ix_pessoas_is_motorista'), table_name='pessoas')
    op.drop_index(op.f('ix_pessoas_is_fornecedor'), table_name='pessoas')
    op.drop_index(op.f('ix_pessoas_is_cliente'), table_name='pessoas')
    op.drop_index(op.f('ix_pessoas_documento'), table_name='pessoas')
    op.drop_index(op.f('ix_pessoas_created_by_id'), table_name='pessoas')
    op.drop_table('pessoas')
    op.drop_index(op.f('ix_pedidos_pesagem_status'), table_name='pedidos_pesagem')
    op.drop_index(op.f('ix_pedidos_pesagem_produto_id'), table_name='pedidos_pesagem')
    op.drop_index(op.f('ix_pedidos_pesagem_numero'), table_name='pedidos_pesagem')
    op.drop_index(op.f('ix_pedidos_pesagem_created_by_id'), table_name='pedidos_pesagem')
    op.drop_index(op.f('ix_pedidos_pesagem_cliente_id'), table_name='pedidos_pesagem')
    op.drop_table('pedidos_pesagem')
    op.drop_index(op.f('ix_pagamentos_pedido_id'), table_name='pagamentos')
    op.drop_index(op.f('ix_pagamentos_numero'), table_name='pagamentos')
    op.drop_index(op.f('ix_pagamentos_created_by_id'), table_name='pagamentos')
    op.drop_index(op.f('ix_pagamentos_cliente_id'), table_name='pagamentos')
    op.drop_table('pagamentos')
    op.drop_index(op.f('ix_ordens_servico_aplicacao_status'), table_name='ordens_servico_aplicacao')
    op.drop_index(op.f('ix_ordens_servico_aplicacao_numero'), table_name='ordens_servico_aplicacao')
    op.drop_index(op.f('ix_ordens_servico_aplicacao_lavoura_id'), table_name='ordens_servico_aplicacao')
    op.drop_index(op.f('ix_ordens_servico_aplicacao_cultura_id'), table_name='ordens_servico_aplicacao')
    op.drop_index(op.f('ix_ordens_servico_aplicacao_created_by_id'), table_name='ordens_servico_aplicacao')
    op.drop_index(op.f('ix_ordens_servico_aplicacao_ano_safra'), table_name='ordens_servico_aplicacao')
    op.drop_table('ordens_servico_aplicacao')
    op.drop_index(op.f('ix_movimentacoes_tipo'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_setor_id'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_produto_id'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_numero'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_modulo'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_maquina_id'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_lote_id'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_gaveta_id'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_estorno_de'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_estornada'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_deposito_id'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_data'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_created_by_id'), table_name='movimentacoes')
    op.drop_index(op.f('ix_movimentacoes_chave_acesso'), table_name='movimentacoes')
    op.drop_table('movimentacoes')
    op.drop_index(op.f('ix_maquinas_deposito_id'), table_name='maquinas')
    op.drop_index(op.f('ix_maquinas_created_by_id'), table_name='maquinas')
    op.drop_index(op.f('ix_maquinas_combustivel_id'), table_name='maquinas')
    op.drop_index(op.f('ix_maquinas_codigo'), table_name='maquinas')
    op.drop_table('maquinas')
    op.drop_index(op.f('ix_lotes_setor_id'), table_name='lotes')
    op.drop_index(op.f('ix_lotes_produto_id'), table_name='lotes')
    op.drop_index(op.f('ix_lotes_maquina_id'), table_name='lotes')
    op.drop_index(op.f('ix_lotes_gaveta_id'), table_name='lotes')
    op.drop_index(op.f('ix_lotes_deposito_id'), table_name='lotes')
    op.drop_index(op.f('ix_lotes_created_by_id'), table_name='lotes')
    op.drop_index(op.f('ix_lotes_codigo_lote'), table_name='lotes')
    op.drop_table('lotes')
    op.drop_index(op.f('ix_lavouras_created_by_id'), table_name='lavouras')
    op.drop_table('lavouras')
    op.drop_index(op.f('ix_inventarios_status'), table_name='inventarios')
    op.drop_index(op.f('ix_inventarios_setor_id'), table_name='inventarios')
    op.drop_index(op.f('ix_inventarios_numero'), table_name='inventarios')
    op.drop_index(op.f('ix_inventarios_created_by_id'), table_name='inventarios')
    op.drop_table('inventarios')
    op.drop_index(op.f('ix_inventario_itens_produto_id'), table_name='inventario_itens')
    op.drop_index(op.f('ix_inventario_itens_inventario_id'), table_name='inventario_itens')
    op.drop_index(op.f('ix_inventario_itens_created_by_id'), table_name='inventario_itens')
    op.drop_table('inventario_itens')
    op.drop_index(op.f('ix_gavetas_deposito_id'), table_name='gavetas')
    op.drop_index(op.f('ix_gavetas_created_by_id'), table_name='gavetas')
    op.drop_index(op.f('ix_gavetas_codigo'), table_name='gavetas')
    op.drop_table('gavetas')
    op.drop_index(op.f('ix_depositos_setor_id'), table_name='depositos')
    op.drop_index(op.f('ix_depositos_numero'), table_name='depositos')
    op.drop_index(op.f('ix_depositos_created_by_id'), table_name='depositos')
    op.drop_table('depositos')
    op.drop_index(op.f('ix_culturas_created_by_id'), table_name='culturas')
    op.drop_table('culturas')
    op.drop_index(op.f('ix_anos_safra_created_by_id'), table_name='anos_safra')
    op.drop_table('anos_safra')
    op.drop_index(op.f('ix_abastecimentos_status'), table_name='abastecimentos')
    op.drop_index(op.f('ix_abastecimentos_produto_id'), table_name='abastecimentos')
    op.drop_index(op.f('ix_abastecimentos_maquina_id'), table_name='abastecimentos')
    op.drop_index(op.f('ix_abastecimentos_created_by_id'), table_name='abastecimentos')
    op.drop_table('abastecimentos')
    # ### end Alembic commands ###
