"""novo nucleo de estoque

Revision ID: a518c4f5ea0b
Revises: e145670a3f1e
Create Date: 2026-09-23 09:36:25.311088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a518c4f5ea0b'
down_revision: Union[str, Sequence[str], None] = 'e145670a3f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estoque_documento_itens',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('documento_id', sa.String(length=100), nullable=False),
    sa.Column('item_numero', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.String(length=100), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unidade', sa.String(length=30), nullable=False),
    sa.Column('deposito_origem_id', sa.String(length=100), nullable=True),
    sa.Column('gaveta_origem_id', sa.String(length=100), nullable=True),
    sa.Column('lote_origem_id', sa.String(length=100), nullable=True),
    sa.Column('deposito_destino_id', sa.String(length=100), nullable=True),
    sa.Column('gaveta_destino_id', sa.String(length=100), nullable=True),
    sa.Column('lote_destino_id', sa.String(length=100), nullable=True),
    sa.Column('custo_unitario', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento_id', 'item_numero', name='uq_estoque_documento_item')
    )
    op.create_index(op.f('ix_estoque_documento_itens_deposito_destino_id'), 'estoque_documento_itens', ['deposito_destino_id'], unique=False)
    op.create_index(op.f('ix_estoque_documento_itens_deposito_origem_id'), 'estoque_documento_itens', ['deposito_origem_id'], unique=False)
    op.create_index(op.f('ix_estoque_documento_itens_documento_id'), 'estoque_documento_itens', ['documento_id'], unique=False)
    op.create_index(op.f('ix_estoque_documento_itens_gaveta_destino_id'), 'estoque_documento_itens', ['gaveta_destino_id'], unique=False)
    op.create_index(op.f('ix_estoque_documento_itens_gaveta_origem_id'), 'estoque_documento_itens', ['gaveta_origem_id'], unique=False)
    op.create_index(op.f('ix_estoque_documento_itens_lote_destino_id'), 'estoque_documento_itens', ['lote_destino_id'], unique=False)
    op.create_index(op.f('ix_estoque_documento_itens_lote_origem_id'), 'estoque_documento_itens', ['lote_origem_id'], unique=False)
    op.create_index(op.f('ix_estoque_documento_itens_produto_id'), 'estoque_documento_itens', ['produto_id'], unique=False)
    op.create_table('estoque_documentos',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('tipo_movimento', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('origem_modulo', sa.String(length=50), nullable=False),
    sa.Column('documento_origem_id', sa.String(length=100), nullable=True),
    sa.Column('referencia_externa', sa.String(length=255), nullable=True),
    sa.Column('data_documento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('contabilizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estornado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usuario_id', sa.String(length=100), nullable=False),
    sa.Column('contabilizado_por_id', sa.String(length=100), nullable=True),
    sa.Column('estornado_por_usuario_id', sa.String(length=100), nullable=True),
    sa.Column('estorno_de_id', sa.String(length=100), nullable=True),
    sa.Column('estornado_por_documento_id', sa.String(length=100), nullable=True),
    sa.Column('motivo_estorno', sa.Text(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estoque_documentos_contabilizado_por_id'), 'estoque_documentos', ['contabilizado_por_id'], unique=False)
    op.create_index(op.f('ix_estoque_documentos_data_documento'), 'estoque_documentos', ['data_documento'], unique=False)
    op.create_index(op.f('ix_estoque_documentos_documento_origem_id'), 'estoque_documentos', ['documento_origem_id'], unique=False)
    op.create_index(op.f('ix_estoque_documentos_estornado_por_documento_id'), 'estoque_documentos', ['estornado_por_documento_id'], unique=False)
    op.create_index(op.f('ix_estoque_documentos_estornado_por_usuario_id'), 'estoque_documentos', ['estornado_por_usuario_id'], unique=False)
    op.create_index(op.f('ix_estoque_documentos_estorno_de_id'), 'estoque_documentos', ['estorno_de_id'], unique=False)
    op.create_index(op.f('ix_estoque_documentos_numero'), 'estoque_documentos', ['numero'], unique=True)
    op.create_index(op.f('ix_estoque_documentos_origem_modulo'), 'estoque_documentos', ['origem_modulo'], unique=False)
    op.create_index(op.f('ix_estoque_documentos_referencia_externa'), 'estoque_documentos', ['referencia_externa'], unique=False)
    op.create_index(op.f('ix_estoque_documentos_status'), 'estoque_documentos', ['status'], unique=False)
    op.create_index(op.f('ix_estoque_documentos_tipo_movimento'), 'estoque_documentos', ['tipo_movimento'], unique=False)
    op.create_index(op.f('ix_estoque_documentos_usuario_id'), 'estoque_documentos', ['usuario_id'], unique=False)
    op.create_table('estoque_saldos',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('produto_id', sa.String(length=100), nullable=False),
    sa.Column('deposito_id', sa.String(length=100), nullable=False),
    sa.Column('gaveta_id', sa.String(length=100), nullable=False),
    sa.Column('lote_id', sa.String(length=100), nullable=False),
    sa.Column('tipo_estoque', sa.String(length=30), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('quantidade_reservada', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('custo_medio', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_id', 'deposito_id', 'gaveta_id', 'lote_id', 'tipo_estoque', name='uq_estoque_saldo_posicao')
    )
    op.create_index(op.f('ix_estoque_saldos_deposito_id'), 'estoque_saldos', ['deposito_id'], unique=False)
    op.create_index(op.f('ix_estoque_saldos_gaveta_id'), 'estoque_saldos', ['gaveta_id'], unique=False)
    op.create_index(op.f('ix_estoque_saldos_lote_id'), 'estoque_saldos', ['lote_id'], unique=False)
    op.create_index(op.f('ix_estoque_saldos_produto_id'), 'estoque_saldos', ['produto_id'], unique=False)
    op.create_index(op.f('ix_estoque_saldos_tipo_estoque'), 'estoque_saldos', ['tipo_estoque'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estoque_saldos_tipo_estoque'), table_name='estoque_saldos')
    op.drop_index(op.f('ix_estoque_saldos_produto_id'), table_name='estoque_saldos')
    op.drop_index(op.f('ix_estoque_saldos_lote_id'), table_name='estoque_saldos')
    op.drop_index(op.f('ix_estoque_saldos_gaveta_id'), table_name='estoque_saldos')
    op.drop_index(op.f('ix_estoque_saldos_deposito_id'), table_name='estoque_saldos')
    op.drop_table('estoque_saldos')
    op.drop_index(op.f('ix_estoque_documentos_usuario_id'), table_name='estoque_documentos')
    op.drop_index(op.f('ix_estoque_documentos_tipo_movimento'), table_name='estoque_documentos')
    op.drop_index(op.f('ix_estoque_documentos_status'), table_name='estoque_documentos')
    op.drop_index(op.f('ix_estoque_documentos_referencia_externa'), table_name='estoque_documentos')
    op.drop_index(op.f('ix_estoque_documentos_origem_modulo'), table_name='estoque_documentos')
    op.drop_index(op.f('ix_estoque_documentos_numero'), table_name='estoque_documentos')
    op.drop_index(op.f('ix_estoque_documentos_estorno_de_id'), table_name='estoque_documentos')
    op.drop_index(op.f('ix_estoque_documentos_estornado_por_usuario_id'), table_name='estoque_documentos')
    op.drop_index(op.f('ix_estoque_documentos_estornado_por_documento_id'), table_name='estoque_documentos')
    op.drop_index(op.f('ix_estoque_documentos_documento_origem_id'), table_name='estoque_documentos')
    op.drop_index(op.f('ix_estoque_documentos_data_documento'), table_name='estoque_documentos')
    op.drop_index(op.f('ix_estoque_documentos_contabilizado_por_id'), table_name='estoque_documentos')
    op.drop_table('estoque_documentos')
    op.drop_index(op.f('ix_estoque_documento_itens_produto_id'), table_name='estoque_documento_itens')
    op.drop_index(op.f('ix_estoque_documento_itens_lote_origem_id'), table_name='estoque_documento_itens')
    op.drop_index(op.f('ix_estoque_documento_itens_lote_destino_id'), table_name='estoque_documento_itens')
    op.drop_index(op.f('ix_estoque_documento_itens_gaveta_origem_id'), table_name='estoque_documento_itens')
    op.drop_index(op.f('ix_estoque_documento_itens_gaveta_destino_id'), table_name='estoque_documento_itens')
    op.drop_index(op.f('ix_estoque_documento_itens_documento_id'), table_name='estoque_documento_itens')
    op.drop_index(op.f('ix_estoque_documento_itens_deposito_origem_id'), table_name='estoque_documento_itens')
    op.drop_index(op.f('ix_estoque_documento_itens_deposito_destino_id'), table_name='estoque_documento_itens')
    op.drop_table('estoque_documento_itens')
    # ### end Alembic commands ###
