"""autenticacao por usuario

Revision ID: a6212a82d5c7
Revises: f57aea43daa4
Create Date: 2026-09-23 08:38:19.442931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6212a82d5c7'
down_revision: Union[str, Sequence[str], None] = 'f57aea43daa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=False))
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'pode_confirmar_abastecimento',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'pode_digitar_peso',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'pode_digitar_peso',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'pode_confirmar_abastecimento',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
