"""consumo parcial de reservas

Revision ID: b21fc76b6fed
Revises: 0212672551d6
Create Date: 2026-09-23 10:00:13.987035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b21fc76b6fed'
down_revision: Union[str, Sequence[str], None] = '0212672551d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estoque_reservas', sa.Column('quantidade_consumida', sa.Numeric(precision=18, scale=3), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estoque_reservas', 'quantidade_consumida')
    # ### end Alembic commands ###
