"""remover transportadora legada

Revision ID: e3e9c6af02d1
Revises: 81ef759bea80
Create Date: 2026-09-23 11:16:27.706479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3e9c6af02d1'
down_revision: Union[str, Sequence[str], None] = '81ef759bea80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transportadoras_created_by_id'), table_name='transportadoras')
    op.drop_index(op.f('ix_transportadoras_documento'), table_name='transportadoras')
    op.drop_index(op.f('ix_transportadoras_nome'), table_name='transportadoras')
    op.drop_table('transportadoras')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transportadoras',
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('documento', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ie', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cidade', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('uf', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('endereco', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('observacao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('transportadoras_pkey'))
    )
    op.create_index(op.f('ix_transportadoras_nome'), 'transportadoras', ['nome'], unique=False)
    op.create_index(op.f('ix_transportadoras_documento'), 'transportadoras', ['documento'], unique=False)
    op.create_index(op.f('ix_transportadoras_created_by_id'), 'transportadoras', ['created_by_id'], unique=False)
    # ### end Alembic commands ###
